Voice Announcement System (website part)
yogstation13/Yogstation.net pull request #2
Opened 2021-06-05 10:23 UTC by monster860

This is the website part of my voice announcement system thingy.

Note for alex the catboy enthusiast: environment variable GAME_VOICE_ANNOUNCE_DIR must be set to like a directory that's shared between the game server and this.

2021-06-05 11:44 UTC, AshCorr requested changes

2021-06-05 11:44 UTC, AshCorr commented on Dockerfile
> +RUN apt-get install -y ffmpeg
Seems like current available version on Debian is ffmpeg v4.1.6 which is currently vulnerable to a RCE vulnerability, see https://www.cvedetails.com/cve/CVE-2021-30123/

2021-06-05 11:45 UTC, AshCorr commented on yogsite/modules/voice_announce/routes.py
> +	id = secure_filename(id)
Awesome

2021-06-05 12:15 UTC, monster860 commented on Dockerfile
> +RUN apt-get install -y ffmpeg
How do I improve this situation

2021-06-05 12:46 UTC, AshCorr commented on Dockerfile
> +RUN apt-get install -y ffmpeg
There isnt really an ideal solution until latest version of ffmpeg is moved into the stable branch.

You can use the experimental branch, but who knows what issues that might have.

```
RUN echo "deb http://deb.debian.org/debian experimental main" >>  /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y -t experimental ffmpeg
```

Or see if theres some alternative / workaround... I couldn't see any listing for a workaround on the CVE though.

2021-06-05 13:06 UTC, AshCorr commented on Dockerfile
> +RUN apt-get install -y ffmpeg
Seems like there are solutions to converting to ogg format which can run in browser.

https://blog.addpipe.com/using-webaudiorecorder-js-to-record-audio-on-your-website/

2021-06-05 13:13 UTC, monster860 commented on Dockerfile
> +RUN apt-get install -y ffmpeg
I still need to use ffmpeg to verify the duration of the sound clip to make sure the user didn't upload like a long-ass sound clip or something

2021-06-05 13:52 UTC, monster860 commented on Dockerfile
> +RUN apt-get install -y ffmpeg
Alright after doing some testing I was able to get the experimental version of ffmpeg to install properly

2021-06-09 01:08 UTC, qwertyquerty commented on yogsite/modules/voice_announce/routes.py
> +	print(res["exists"])
dont forget to get rid of these

2021-06-13 11:45 UTC, JamieD1 commented
Ash is going to kill me

2021-06-13 11:45 UTC, merged